/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as ListingsIdImport } from './routes/listings_.$id'
import { Route as LayoutListingsImport } from './routes/_layout.listings'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ListingsIdRoute = ListingsIdImport.update({
  path: '/listings/$id',
  getParentRoute: () => rootRoute,
} as any)

const LayoutListingsRoute = LayoutListingsImport.update({
  path: '/listings',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/listings': {
      preLoaderRoute: typeof LayoutListingsImport
      parentRoute: typeof LayoutImport
    }
    '/listings/$id': {
      preLoaderRoute: typeof ListingsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([LayoutListingsRoute]),
  ListingsIdRoute,
])

/* prettier-ignore-end */
