/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ListingsImport } from './routes/listings'
import { Route as IndexImport } from './routes/index'
import { Route as ListingsIdImport } from './routes/listings_.$id'

// Create/Update Routes

const ListingsRoute = ListingsImport.update({
  path: '/listings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ListingsIdRoute = ListingsIdImport.update({
  path: '/listings/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/listings': {
      preLoaderRoute: typeof ListingsImport
      parentRoute: typeof rootRoute
    }
    '/listings/$id': {
      preLoaderRoute: typeof ListingsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ListingsRoute,
  ListingsIdRoute,
])

/* prettier-ignore-end */
